(define carnivoro
  (lambda (ls)
    (if (null? ls)
        '()
        (if (or (equal? (cadar ls) "carnivoro")(equal? (cadar ls) "ambos"))
            (cons (car ls) (carnivoro (cdr ls)))
            (carnivoro (cdr ls))
            )
        )
    )
  )
(define vegetariano
  (lambda (ls)
    (if (null? ls)
        '()
        (if (or (equal? (cadar ls) "vegetariano")(equal? (cadar ls) "ambos"))
            (cons (car ls) (vegetariano (cdr ls)))
            (carnivoro (cdr ls))
            )
        )
    )
  )
;(carnivoro '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))
;(vegetariano '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))

;Funcion Auxiliar
(define menor
  (lambda (ls)
        (if (null? (cdr ls))
            (car ls)
            (if (< (caddar ls)  (caddr (menor (cdr ls)))) 
                (car ls)
                (menor (cdr ls))
                )
            )
        )
    )
  
(define eliminar
  (lambda (e ls)
    (if (null? ls)
        '()
        (if (equal? e (caar ls))
            (cdr ls)
            (cons (car ls) (eliminar e (cdr ls)))
            ) 
        )
    )
  )
;(eliminar "milanesa de carne" '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))

(define ordenar
  (lambda (ls)
    (if (null? ls)
        '()
        (cons (menor ls) (ordenar (eliminar (car (menor ls)) ls)))
        )
    )
  )
;(ordenar '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))

(define CaloriasMax
  (lambda (ls)
    (if (null? ls)
        '()
        (letrec ((agregados (lambda (ls2 calorias sumados)
                              (if (null? ls2)
                                  '()
                                  (if (< (+ (caddar ls2) calorias) 500)
                                      (agregados (cdr ls2) (+ (caddar ls2) calorias) (car ls2))
                                      sumados)
                                  )
                              )
                            ))
          (agregados ls 0 '())
          )
        )
    )
  )
(CaloriasMax (ordenar (vegetariano '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))))

(define dieta
  (lambda (ls)
    (if (null? ls)
        '()
        (cons (CaloriasMax (ordenar (vegetariano ls))) (list (CaloriasMax (ordenar (carnivoro ls)))))
        )
    )
  )
(dieta '(("papa" "vegetariano" 80) ("milanesa de carne" "carnívoro" 150) ("jugo de naranja" "vegetariano" 70) ("calabaza" "vegetariano" 90) ("costeleta" "carnívoro" 180) ("tiramisú" "ambos" 150) ("pastas" "ambos" 100) ("gaseosa" "ambos" 220) ("pan" "ambos" 110) ("chocolate" "ambos" 400) ("espárragos" "vegetariano" 60) ("empanadas de carne" "carnívoro" 200)))